### ISSUE TITLE
Does not work behind a velocity/bungeecord proxy

### ISSUE THREAD

**Issue by OfficiallySp** [worldbiomusic/wbmMC#1]
whenever i try to add this dependency. i get the following error
Unknown data in login hostname, did you forget to enable BungeeCord in spigot.yml?

**Comment by worldbiomusic** [comment]
@OfficiallySp 
I have run this plugin with other plugins in single bukkit and bungeecord without error.

And I think that error(**Unknown data in login hostname**) is related with your server settings.
Hope [this](https://www.spigotmc.org/threads/help-unknown-hostname.66663/) helpful to you.
